# Generated by Django 2.2 on 2021-04-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPortrait', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPortrait',
        ),
    ]
