# Generated by Django 2.2 on 2021-05-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortrait', '0003_userportrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportrait',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userportrait',
            name='gender_probability',
        ),
        migrations.AddField(
            model_name='userportrait',
            name='female_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userportrait',
            name='male_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
