# Generated by Django 2.2.19 on 2021-04-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weibo_user_id', models.CharField(max_length=32, unique=True)),
                ('screen_name', models.CharField(max_length=64, unique=True)),
                ('gender', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=256)),
                ('statuses_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('follow_count', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar_hd', models.CharField(max_length=256)),
                ('weibo_rank', models.IntegerField()),
                ('member_rank', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('since_date', models.DateTimeField()),
                ('last_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'WeiboUser',
            },
        ),
        migrations.CreateModel(
            name='WeiboText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weibo_text_id', models.CharField(max_length=32, unique=True)),
                ('text', models.TextField()),
                ('topic', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('tool', models.CharField(max_length=64)),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('repost_count', models.IntegerField()),
                ('is_original', models.BooleanField(default=True)),
                ('source_text', models.TextField()),
                ('source_topic', models.CharField(max_length=128)),
                ('weibo_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiboCrawler.WeiboUser', to_field='weibo_user_id')),
            ],
            options={
                'db_table': 'WeiboText',
            },
        ),
    ]
