# Generated by Django 2.2.19 on 2021-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibotext',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weibotext',
            name='source_topic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
