# Generated by Django 2.2.19 on 2021-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0002_auto_20210413_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibotext',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='weibotext',
            name='source_text',
        ),
        migrations.RemoveField(
            model_name='weibotext',
            name='source_topic',
        ),
        migrations.AddField(
            model_name='weibotext',
            name='retweet_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='weibouser',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
