# Generated by Django 2.2.19 on 2021-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0003_auto_20210413_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibotext',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
