# Generated by Django 2.2.19 on 2021-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0004_auto_20210413_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
