# Generated by Django 2.2.19 on 2021-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0005_auto_20210413_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weibouser',
            name='since_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
