# Generated by Django 2.2.19 on 2021-04-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0007_remove_weibouser_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibotext',
            name='retweet_id',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='weiboCrawler.WeiboText'),
        ),
        migrations.AlterField(
            model_name='weibotext',
            name='weibo_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weibo_text_user', to='weiboCrawler.WeiboUser'),
        ),
    ]
