# Generated by Django 2.2.19 on 2021-04-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0008_auto_20210413_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibotext',
            old_name='retweet_id',
            new_name='retweet',
        ),
        migrations.RenameField(
            model_name='weibotext',
            old_name='weibo_user_id',
            new_name='weibo_user',
        ),
    ]
