# Generated by Django 2.2.19 on 2021-04-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0010_remove_weibotext_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibotext',
            name='retweet',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='weiboCrawler.WeiboText', to_field='weibo_text_id'),
        ),
    ]
