# Generated by Django 2.2 on 2021-04-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0014_auto_20210413_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibouser',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='weibouser',
            name='portrait_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
