# Generated by Django 2.2 on 2021-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0015_auto_20210421_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibouser',
            name='portrait_status',
            field=models.BooleanField(default=False),
        ),
    ]
