# Generated by Django 2.2 on 2021-04-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0016_auto_20210425_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibotext',
            name='weibo_user',
        ),
    ]
