# Generated by Django 2.2 on 2021-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0018_weibotext_weibo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibouser',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
