# Generated by Django 2.2 on 2021-05-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weiboCrawler', '0019_weibouser_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibouser',
            old_name='profile_image_url',
            new_name='profile_url',
        ),
    ]
